### ISSUE TITLE
Leaks on panic

### ISSUE THREAD

**Issue by henninglive** [Manishearth/array-init#10]
If I am not misunderstanding something, this crate will not run destructors for initialized elements if we panic while filling the array. This should probably be mentioned in the docs.

Is this something that could be fixed? One-way i can think of is to wrap the nodrop array with a new struct adding a length, then when the new struct is dropped, we drop all initialized elements. The [arrayvec](https://github.com/bluss/arrayvec) crate works like this, but when unwrapping an arrayvec into an array it generates two memcpys `arrayvec -> result -> array`. It’s difficult to avoid the memcpys.

**Comment by Manishearth** [comment]
This is intentional; I wanted to avoid more memcpys.

I'll document this.

**Comment by henninglive** [comment]
Fair enough, but the same applies to `from_iter()`, so maybe add warning there too.
