### ISSUE TITLE
Cant initialize with negative values i32 table

### ISSUE THREAD

**Issue by michalwidera** [Manishearth/array-init#15]
Look's like

 let array_a: [i32; 20] = array_init::array_init(|i| (i) as i32);

works fine, but

let array_b: [i32; 20] = array_init::array_init(|i| (i*(-1)) as i32);

is reporting

   |
26 |     let array_b: [i32; 20] = array_init::array_init(|i| (i*(-1)) as i32);
   |                                                            ^^^^ the trait `std::ops::Neg` is not implemented for `usize`

Negative values initialization proble occured.
(fresh&new in Rust ... apologies if something misunderstood)

**Comment by Manishearth** [comment]
you need to cast `i` to `i32` first
