### ISSUE TITLE
Unclear security guarantees regarding pointer arithmetic in unsafe code

### ISSUE THREAD

**Issue by krtab** [Manishearth/array-init#19]
Hi,

Currently in `try_array_init`, in the code for both the "need drop" and "needs not drop" cases, there are the following comments:

https://github.com/Manishearth/array-init/blob/ffb5f8ed8d7532c15109cdfa6b899058a7ee5acc/src/lib.rs#L155-L156

https://github.com/Manishearth/array-init/blob/ffb5f8ed8d7532c15109cdfa6b899058a7ee5acc/src/lib.rs#L205-L206

which are reformulations of those, originally written by @vorner:

https://github.com/Manishearth/array-init/blob/d1279d6d4cc0b271122bd054a00d07c68c3a111c/src/lib.rs#L97-L99

https://github.com/Manishearth/array-init/blob/d1279d6d4cc0b271122bd054a00d07c68c3a111c/src/lib.rs#L138-L140

I'm not sure of what these comments mean and what are their implications in terms of safety. Especially, `pointer::add` has the following code:

```rust
    pub const unsafe fn add(self, count: usize) -> Self
    where
        T: Sized,
    {
        // SAFETY: the caller must uphold the safety contract for `offset`.
        unsafe { self.offset(count as isize) }
    }
```

which states that *the caller must uphold the safety contract for `offset`*, safety contract which [is](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.offset), if I'm correct:

> If any of the following conditions are violated, the result is Undefined Behavior:
> 
>   - Both the starting and resulting pointer must be either in bounds or one byte past the end of the same allocated object. Note that in Rust, every (stack-allocated) variable is considered a separate allocated object.
> 
>   - The computed offset, in bytes, cannot overflow an isize.
> 
>   - The offset being in bounds cannot rely on "wrapping around" the address space. That is, the infinite-precision sum, in bytes must fit in a usize.

From  my understanding, the risk would be that `Array::Item` has a size (in bytes) greater than `isize::MAX`, because we only increase the pointer by 1. Yet, the reference [states](https://doc.rust-lang.org/stable/reference/types/numeric.html#machine-dependent-integer-types) that:

> The isize type is a signed integer type with the same number of bits as the platform's pointer type. The theoretical upper bound on object and array size is the maximum isize value. This ensures that isize can be used to calculate differences between pointers into an object or array and can address every byte within an object along with one byte past the end.

Hence, I'm not sure that any overflow can happen here. That being said, if it can happen, I don't think using `add` rather than `offset` safeguards against it.

Let me know if I can help in any way

**Comment by vorner** [comment]
Hello

The fear was that it's possible to have a huge array. Let's say you have an array of 4-byte elements, but have them 2^30+1 on 32 bit system. The *count* of these still fit into `isize`, but the offset of the last element from the *beginning* does not (I've probably made some +- mistakes or something, the idea is that count of element fits, size of the whole array doesn't).

Using `add(1)` to step by these 4 bytes means that you never „jump“ by more than what fits into isize. You could surely use `offset(1)` from the last position, what you don't want to do is  offset from the beginning. The difference is not between `offset` vs `add`, but between `1` (relative to last iteration) vs `pos` (relative to beginning).

That was what was meant by my original comment, I haven't checked what the current state of code is. Does that make sense?

Edit: I'm not sure the code is not older than this note in reference, or if I knew about this note in reference. But the current code is erroring on the safe side and assuming even bigger arrays can in theory exist and it won't cause UB to them. Furthermore, if the part in the reference is true, then the second point of the security considerations of offset is meaningless and leads directly from the first point.

**Comment by krtab** [comment]
> The fear was that it's possible to have a huge array. Let's say you have an array of 4-byte elements, but have them 2^30+1 on 32 bit system. The count of these still fit into isize, but the offset of the last element from the beginning does not (I've probably made some +- mistakes or something, the idea is that count of element fits, size of the whole array doesn't).

Indeed, I had not realized but the code logic has changed since your implementation.

It seems the overflowing unsoundness has been fixed by @danielhenrymantilla in https://github.com/Manishearth/array-init/commit/c026935e360190418ccc90b116f8dc2747034588

I don't have a non-64-pointer-sized to check, but I think it is fair to assume that an array element cannot be more than `isize::MAX` byte from the reference I have quoted above, and hence that these comments can simply be deleted.

Thanks a lot for your quick answer!

**Comment by vorner** [comment]
> but I think it is fair to assume that an array element

My fear at the time was that both the count of elements and size of single element are indeed smaller than `isize::MAX`, but the whole array itself would be larger (eg. `count * sizeof(element) > isize::MAX`). That's probably forbidden by that reference too, though :shrug:

**Comment by Manishearth** [comment]
Thanks for your comments @vorner !
