### ISSUE TITLE
Please add something like from_reversed_iter

### ISSUE THREAD

**Issue by glandium** [Manishearth/array-init#30]
Not all iterators are DoubleEndedIterator, and thus it's not always possible to `array_init::from_iter(iter.rev())`.
Even though the compiler can probably optimize it out (but can also miss the opportunity for random reasons), it's cumbersome to do something like
```
let array: [_; N] = array_init::from_iter(iter);
let result = array_init::from_iter(array.iter().copied().rev());
```
when array_init could do it directly, and avoid the optimizer having to figure it out on its own.

**Comment by Manishearth** [comment]
Happy to accept a PR, but it would still need to be ExactSize

**Comment by glandium** [comment]
It doesn't need to be if you initialize elements in the inverse order. The question is how to reasonably make try_array_init (or a private variant of it) take the direction in which to go.

**Comment by Manishearth** [comment]
@glandium how would you know how much stack space to preallocate?

**Comment by Manishearth** [comment]
Oh! I see with the try_ functions. Right, makes sense, I got confused for a bit
