### ISSUE TITLE
MSRV policy

### ISSUE THREAD

**Issue by jschwe** [Manishearth/array-init#39]
Hi,

Currently it seems this crate compiles down to Rust 1.51 (const generics). Would it be possible to add an official MSRV policy, so that we can use this crate in downstream projects with an MSRV policy?

**Comment by Manishearth** [comment]
Given that this crate does not change often I'm open to this.

What I would need to accept this would be a PR that adds CI for 1.51 (we should still CI nightly though), and also the rust-version key in Cargo.toml.

**Comment by Manishearth** [comment]
The main hazard is that we may need const generic features that aren't yet supported. It is worth considering something like 1.62ish that has a more filled out slate of const generics. What version is typical for crates pinning an MSRV these days?

**Comment by jschwe** [comment]
I would like to use this crate in a PR for tokio, which currently supports Rust 1.49, but the maintainers have indicated that a bump to 1.51 would be possible.

Most crates have an official policy of 6 months, but in practice update the MSRV conservatively.

>  It is worth considering something like 1.62ish that has a more filled out slate of const generics

For my current use case the crate is sufficient as is, so the only thing I would request is to bump the version number when updating the MSRV and to announce it in the changelog. Personally I prefer bumping the major number on MSRV change (since I consider it a breaking change), but many crates document that MSRV bumps are allowed on MINOR version increases. As long as it is properly documented and I know what to expect I can live with that too.

**Comment by Manishearth** [comment]
Sounds good.

How about we do the following:

 - set MSRV to 1.51
 - Document that we may do MSRV bumps on minor bumps, BUT that we don't expect it to be likely
 - Revisit this in the future and perhaps strengthen the policy

**Comment by Manishearth** [comment]
Fixed in #40, and also published 2.1.0
