### ISSUE TITLE
Export the impl_is_array! macro

### ISSUE THREAD

**Issue by jatentaki** [Manishearth/array-init#4]
The IsArray trait states that `Probably shouldn't implement this yourself, but you can`. Internally you use impl_is_array! for N=0,..64, but I would like to use the crate for arrays [T; 1000].
Is there a reason why this macro isn't exposed in the API?

**Comment by Manishearth** [comment]
> but I would like to use the crate for arrays [T; 1000]. Is there a reason why this macro isn't exposed in the API?

Coherence won't let you implement it yourself anyway. It's completely useless outside of the crate.


You really should be using a heap allocation for something that large. While this crate tries to avoid copies, it's not going to help you avoid copies elsewhere.
